version: '3'
services:

  backend:
    image: registry.gitlab.com/monixm/last-propulsion-project
    restart: always
    networks:
      - nginx_network
      - database1_network
    env_file:
      - prod.env
    command: 'sh /scripts/run.sh'
    volumes:
      - frontend:/frontend-build
      - static-files:/static-files
      - media-files:/media-files
    depends_on:
      - database

  database:
    image: postgres:latest
    restart: always
    env_file:
      - prod.env
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - database1_network

  nginx:
    image: nginx:latest
    volumes:
      - static-files:/static-files
      - media-files:/media-files
      - ./config:/etc/nginx/conf.d
      - frontend:/frontend
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    command: /bin/bash -c "nginx -g 'daemon off;'"
    depends_on:
      - backend
    networks:
      - nginx_network

networks:  # <-- and here
  nginx_network:
    driver: bridge
  database1_network:  # <-- add the bridge
    driver: bridge

volumes:
  frontend:
  database:
  static-files:
  media-files:
